name: ci

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  cmake_build:
    name: cmake_build
    runs-on: ubuntu-latest

    steps:
      - name: setup
        run: |
         sudo apt-get update
         sudo apt-get install build-essential cmake g++ clang-15 libgtest-dev libgmock-dev make
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Generate makefile using CMake
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_CXX_COMPILER=/usr/bin/clang++-15
      - name: Run make
        run: |
          cd build
          make -j$(nproc)
      - name: Run unittests
        run: |
          cd build
          ctest -j$(nproc)